### ISSUE TITLE
Link errors in XCode

### ISSUE THREAD

**Issue by jprider63** [TimNN/cargo-lipo#11]
When I attempt to build my project in XCode, I get the following errors when linking my rust library: 

```
Undefined symbols for architecture armv7:
  "__aeabi_idiv", referenced from:
      ___aeabi_idivmod in libmyrust_c.a(compiler_builtins-f6c69d64299ff1c7.compiler_builtins0.rcgu.o)
     (maybe you meant: ___aeabi_idiv, ___aeabi_idivmod )
  "__divmoddi4", referenced from:
      ___aeabi_ldivmod in libmyrust_c.a(compiler_builtins-f6c69d64299ff1c7.compiler_builtins0.rcgu.o)
     (maybe you meant: ___divmoddi4)
  "__udivmoddi4", referenced from:
      ___aeabi_uldivmod in libmyrust_c.a(compiler_builtins-f6c69d64299ff1c7.compiler_builtins0.rcgu.o)
     (maybe you meant: ___udivmoddi4)
  "__udivmodsi4", referenced from:
      ___aeabi_uidivmod in libmyrust_c.a(compiler_builtins-f6c69d64299ff1c7.compiler_builtins0.rcgu.o)
     (maybe you meant: ___udivmodsi4)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

It looks like it can't find some symbols, but can find variants with three underscores. I'm not sure if this is a lipo error or not. I am using [ring](https://github.com/briansmith/ring) in my rust library. Do you have any ideas why this might be failing? 

These are the versions I have installed:

```
$ cargo --version
cargo 0.24.0 (45043115c 2017-12-05)
$ cargo lipo --version
cargo-lipo 1.0.1
```

**Comment by TimNN** [comment]
Could you provide the output of `rustc -vV` as well please?

Looking at the error message, I don't think that `ring` is (directly) at fault. If easily possible, could you try compiling without `ring`?

IIRC, the C-ABI dictates that certain names are prefixed with _, so my best guess right now is that something changed in rustc or llvm which broke things.

**Comment by jprider63** [comment]
To debug, I've removed `ring` as a dependency and added the following dummy function. 

```
#[no_mangle]
pub extern fn div11( x : i32) -> i32 {
    x / 11
}
```

I still get the same error.

**Comment by TimNN** [comment]
Thanks for the info!

I'll look into this today or Monday and get back to you.

One last question: What's you macOS / XCode version?

**Comment by jprider63** [comment]
Great thanks! I'm running macOS 10.13.3 with XCode 9.2.

**Comment by TimNN** [comment]
Hi @jprider63, I just tried to reproduce the error and couldn't.

Could provide some more detailed instructions on what you are doing?

* What's in your `Cargo.toml` file?
* What arguments are you passing to `cargo lipo`
* How are you linking the library to XCode?
* Are you linking anything else into your binary?
* Do you have any special configuration for the XCode project? Target architecture / iOS version?

If possible, could you provide a git repository with the reproduction with the `div11` example?

**Comment by jprider63** [comment]
The project is in the debug branch of [this repository](https://github.com/PKAuth/rs-pkauth-c/tree/debug). You can find staticpublicsuffix [here](https://github.com/jprider63/staticpublicsuffix).

I think the `Cargo.toml` is pretty standard. The main thing is I added `crate-type = ["staticlib"]` to generate static libraries. I'm running `cargo lipo --release`. 

I added the `.a` and `.h` file to my XCode project. I also added the `.a` file to "Linked Frameworks and Libraries" under "General" project settings. I'm also linking `libresolv.tbd` and `libiconv.dylib`. I'm not sure if the latter is required. I can try removing it. 

I only get the error when compiling for an iPhone 6S (armv7).

**Comment by TimNN** [comment]
I still cannot reproduce :(

I did the following:

* Checkout both repositories and adjust some paths
* Create an XCode Project (iOS Single-Page App, Objective-C)
* Call `printf("FOO: %d\n", div11(32))` in `main.m`
* `make build-ios && make deploy-ios`
* Add the `.a` and `.h` files to XCode, this added the `.a` file to "Linked Frameworks and Libraries"
* Add `libresove.tbd` to "Linked Frameworks and Libraries"
* Set `ENABLE_BITCODE` to "NO" in the build settings
* Connect an iPhone 6 (I don't have the 6S) and press "Run"
* **`=>`** Everything builds fine.
* All of that on `rustc 1.23.0 (766bd11c8 2018-01-01)`

**Comment by jprider63** [comment]
If I change "Build Active Architecture Only" to `Yes` under "Build Settings", the build succeeds for me. What happens if you set this to `No`? 

Alternatively, if I remove `armv7` from "Valid Architectures", the build also succeeds. Are you able to compile for armv7? 

I can send you the `.a` file that my machine generates if it'd be helpful.

**Comment by TimNN** [comment]
I did the following, in addition to what I wrote above:

* Set "Build Active Architectures Only" to `No`
* Set "Valid Architectures" to `armv7`
* Set "Architectures" to `armv7`
* Set "iOS Deployment Target" to `iOS 10.3`

Please send me the `.a` file and I'll try with that / compare that to mine. You can find my email on my profile page, or use `mail@$GITHUB_USERNAME.me`.

**Comment by TimNN** [comment]
I left that comment half-finished...

---

I still cannot reproduce. (I performed the "Build" action for "Generic iOS Device" and tried "Archive" as well. Both compiled without issue for me.

**Comment by TimNN** [comment]
I still can't reproduce with the library you sent, however I did look at the output of `nm` and things seem to be indeed broken, I'll look into that.

Could you please try compiling with the latest nightly, just in case the issue has been fixed?

**Comment by TimNN** [comment]
Opened https://github.com/rust-lang-nursery/compiler-builtins/issues/237

**Comment by TimNN** [comment]
It seems that this is indeed a bug in `compiler-builtins`. I have a potential fix in https://github.com/rust-lang-nursery/compiler-builtins/pull/238. If all goes well that should be in nightly in the next few days.

**Comment by TimNN** [comment]
@jprider63, some more info: Only the `armv7*` (32-bit ARM) targets seem to be affected. That means that as long as you only target "iPhone 5S" and newer, those targets should be fine. (In fact, if you set the "Deployment Target" to `iOS 11.*`, XCode refuses to build for `armv7*` for me).

**Comment by jprider63** [comment]
Awesome, thanks @TimNN! I just compiled with nightly (ae544ee1c 2018-03-29) and everything seems to be working.
