### ISSUE TITLE
cannot find function `_Unwind_Backtrace` in module `uw`

### ISSUE THREAD

**Issue by sintanial** [TimNN/cargo-lipo#16]
When i try compile my library with ```cargo lipo --release``` i receive this error 
```rust
error[E0425]: cannot find function `_Unwind_Backtrace` in module `uw`
  --> /Users/test/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.2.3/src/backtrace/libunwind.rs:54:13
   |
54 |         uw::_Unwind_Backtrace(trace_fn, &mut cb as *mut _ as *mut _);
   |             ^^^^^^^^^^^^^^^^^ not found in `uw`

error: aborting due to previous error
```

how to fix this ?

**Comment by TimNN** [comment]
Can you provide some more information, please? Is the code public somewhere so I can try to reproduce? Which rustc --version are you using? What is the output of cargo when you build with --verbose? What is the exact target triple that fails?

From the error you posted it looks like one of your dependencies does not support iOS.

**Comment by sintanial** [comment]
Yes, your right. It's problem in one of dependencies which use old backtrace library, sorry for this issue
