### ISSUE TITLE
Release a 1.0.4 for removing `armv7s-apple-ios`

### ISSUE THREAD

**Issue by seivan** [TimNN/cargo-lipo#23]
Since there's only a single master branch, is there a way to have a branch for 1.0.4 and also release it as a crate as the beta is still under development and not installed by default unless you ask for it? 

I don't need `armv7s-apple-ios` but `1.0.3` requires it

I could do the change myself if needed.

**Comment by TimNN** [comment]
I've just released a `2.0.0`. It didn't have any of the changes I was planning to implement at some point, but it should nevertheless also take care of this issue, I think.

**Comment by seivan** [comment]
@TimNN Thanks!
