### ISSUE TITLE
Release 2.0 version

### ISSUE THREAD

**Issue by eoger** [TimNN/cargo-lipo#24]
Would it be possible to release the 2.0 version on crates.io or is it still missing some stuff?
We have to use `cargo install --force --git https://github.com/TimNN/cargo-lipo` to get a proper version of cargo lipo, which is not super obvious for new contributors.
Thank you!

**Comment by TimNN** [comment]
Yeah, that probably makes sense, I'll put it on the to-do list for the weekend :)

**Comment by eoger** [comment]
Awesome thanks!

**Comment by TimNN** [comment]
I've released `2.0.0`.
