### ISSUE TITLE
Final step fails when package name contains a dash

### ISSUE THREAD

**Issue by bbqsrc** [TimNN/cargo-lipo#32]
A package with the name `foo-bar` will create a `foo_bar.a`, but cargo-lipo tries to link against `foo-bar.a` and fails.

**Comment by DagAgren** [comment]
https://github.com/TimNN/cargo-lipo/pull/30 seems to fix this.

**Comment by TimNN** [comment]
Published 3.1.0 with #30, which should fix this issue. Please add a comment if it still does not.
