### ISSUE TITLE
Xcode 13 and M1 chips introduce a new SDK for simulation builds

### ISSUE THREAD

**Issue by brotskydotcom** [TimNN/cargo-lipo#52]
With Xcode 13 on M1 chips, there is a new SDK used for simulator builds on aarch64 (that is, the SDK is different from builds that run on actual hardware).  Rust supports this new SDK with the `-sim` ABI addition to the `aarch64-apple-ios` triple, so builds whose platform contains the word "simulator" (as in "iphonesimulator" as opposed to "iphoneos") need to be done with the `aarch64-apple-ios-sim` target.

Complicating this is the fact that lipo doesn't distinguish these libraries from other aarch64 libraries, so it can't put a _simulator_ SDK library and a _standard_ SDK library in the same archive.  Thus there's no way to build all the architectures into one library.

It's not exactly clear how lipo could handle this outside of the Xcode integration context.  But at least in that context it should be able to choose the right library based on the targets being built.  I'm going to submit a PR to ad this little logic.

**Comment by chrisballinger** [comment]
Yes - you can't lipo together the arm64 iOS simulator and arm64 iOS device slices, you must use xcframeworks instead. Lipo together all of the archs for each device type, and then create an xcframework from multiple fat static libs.

Here is a pretty decent resource: https://github.com/bielikb/xcframeworks
